In [1]:
from r2b2.contest import Contest, ContestType
from r2b2.minerva import Minerva
import r2b2.contest as contest
import r2b2.tests.util as util
import numpy as np

## First example: calculate values for 50% margin contest ala illustrative graph

TODO: How to handle audit with arbitrary observations via non-interactive code

In [2]:
c = Contest(10000, {
'A': 7500,
       'B': 2500
    }, 1, ['A'], ContestType.PLURALITY)

In [3]:
# Alternative:
# c = util.parse_contest('r2b2/tests/data/m50-contest.json')

In [4]:
c

Contest: [10000, {'A': 7500, 'B': 2500}, 1, ['A'], <ContestType.PLURALITY: 0>]

In [5]:
m = Minerva(0.1, 0.5, c)

In [6]:
m

Minerva: [0.1, 0.0, 0.5, True, Contest: [10000, {'A': 7500, 'B': 2500}, 1, ['A'], <ContestType.PLURALITY: 0>]]

In [7]:
m.get_min_sample_size()

6

In [8]:
m.asn()

20

In [9]:
m.compute_min_winner_ballots([50])

In [10]:
m.min_winner_ballots

[31]

It seems that the code should catch this case, with a helpful error message about running current_dist_reported()?

In [11]:
m.compute_risk(32)

ZeroDivisionError: division by zero

In [12]:
m.current_dist_reported()

In [13]:
m.distribution_reported_tally

array([  7.88860905e-31,   1.18329136e-28,   8.69719148e-27,
         4.17465191e-25,   1.47156480e-23,   4.06151884e-22,
         9.13841740e-21,   1.72324442e-19,   2.77873163e-18,
         3.89022429e-17,   4.78497587e-16,   5.21997368e-15,
         5.08947434e-14,   4.46307750e-13,   3.53858287e-12,
         2.54777967e-11,   1.67198041e-10,   1.00318824e-09,
         5.51753534e-09,   2.78780733e-08,   1.29633041e-07,
         5.55570175e-07,   2.19702751e-06,   8.02392656e-06,
         2.70807521e-05,   8.44919467e-05,   2.43726769e-04,
         6.49938052e-04,   1.60163306e-03,   3.64509592e-03,
         7.65470143e-03,   1.48155512e-02,   2.63902005e-02,
         4.31839645e-02,   6.47759467e-02,   8.88355840e-02,
         1.11044480e-01,   1.26050491e-01,   1.29367609e-01,
         1.19416254e-01,   9.85184099e-02,   7.20866414e-02,
         4.63414123e-02,   2.58649743e-02,   1.23446468e-02,
         4.93785874e-03,   1.61017133e-03,   4.11107573e-04,
         7.70826699e-05,

In [14]:
len(m.distribution_reported_tally)

51

In [15]:
m.distribution_null

array([  8.88178420e-16,   4.44089210e-14,   1.08801856e-12,
         1.74082970e-11,   2.04547490e-10,   1.88183691e-09,
         1.41137768e-08,   8.87151685e-08,   4.76844031e-07,
         2.22527214e-06,   9.12361579e-06,   3.31767847e-05,
         1.07824550e-04,   3.15179455e-04,   8.32974273e-04,
         1.99913826e-03,   4.37311493e-03,   8.74622987e-03,
         1.60347548e-02,   2.70059027e-02,   4.18591493e-02,
         5.97987846e-02,   7.88256707e-02,   9.59616860e-02,
         1.07956897e-01,   1.12275173e-01,   1.07956897e-01,
         9.59616860e-02,   7.88256707e-02,   5.97987846e-02,
         4.18591493e-02])

In [16]:
len(m.distribution_null)

31

In [17]:
m.current_dist_null()

In [18]:
m.distribution_null

array([  8.88178420e-16,   4.44089210e-14,   1.08801856e-12,
         1.74082970e-11,   2.04547490e-10,   1.88183691e-09,
         1.41137768e-08,   8.87151685e-08,   4.76844031e-07,
         2.22527214e-06,   9.12361579e-06,   3.31767847e-05,
         1.07824550e-04,   3.15179455e-04,   8.32974273e-04,
         1.99913826e-03,   4.37311493e-03,   8.74622987e-03,
         1.60347548e-02,   2.70059027e-02,   4.18591493e-02,
         5.97987846e-02,   7.88256707e-02,   9.59616860e-02,
         1.07956897e-01,   1.12275173e-01,   1.07956897e-01,
         9.59616860e-02,   7.88256707e-02,   5.97987846e-02,
         4.18591493e-02,   2.70059027e-02,   1.60347548e-02,
         8.74622987e-03,   4.37311493e-03,   1.99913826e-03,
         8.32974273e-04,   3.15179455e-04,   1.07824550e-04,
         3.31767847e-05,   9.12361579e-06,   2.22527214e-06,
         4.76844031e-07,   8.87151685e-08,   1.41137768e-08,
         1.88183691e-09,   2.04547490e-10,   1.74082970e-11,
         1.08801856e-12,

In [19]:
len(m.distribution_null)

51

In [20]:
m.compute_risk(32)

0.033414425566758013

In [21]:
[(obs, m.compute_risk(obs)) for obs in range(0, 35)]

[(0, 0.999999999999995),
 (1, 0.99999999999999412),
 (2, 0.99999999999994971),
 (3, 0.99999999999886169),
 (4, 0.99999999998145339),
 (5, 0.9999999997769059),
 (6, 0.99999999789506899),
 (7, 0.99999998378129218),
 (8, 0.99999989506612363),
 (9, 0.99999941822209271),
 (10, 0.99999719294994838),
 (11, 0.99998806933415707),
 (12, 0.9999548925494649),
 (13, 0.99984706799924983),
 (14, 0.9995318885450718),
 (15, 0.99869891427567015),
 (16, 0.99669977604601134),
 (17, 0.9923266612788878),
 (18, 0.98358043239806459),
 (19, 0.96754568296328991),
 (20, 0.94053980625873534),
 (21, 0.89868077205676977),
 (22, 0.83888244364773945),
 (23, 0.76005838610907794),
 (24, 0.66410174889038454),
 (25, 0.55615873232159985),
 (26, 0.44391679944973528),
 (27, 0.33602858406556296),
 (28, 0.24018790457911424),
 (29, 0.16154104415410725),
 (30, 0.10195792858213848),
 (31, 0.060299450434402241),
 (32, 0.033414425566758013),
 (33, 0.017377473516471977),
 (34, 0.0085099270818493385)]

In [22]:
m.stopping_prob_schedule

[0.9860823913213379]

In [23]:
m.rounds

[50]

Show peak values of distributions, along with the index

In [24]:
amn = np.argmax(m.distribution_null)

In [25]:
amn, m.distribution_null[amn]

(25, 0.11227517265921609)

In [26]:
amr = np.argmax(m.distribution_reported_tally)

In [27]:
amr, m.distribution_reported_tally[amr]

(38, 0.12936760901135547)

TODO: ability to estimate sample size given stopping probability

In [28]:
m.next_sample_size()

This is currently only set for interactive runs, it seems

In [29]:
m.sample_winner_ballots

[]

## Another example, reading in an election

In [30]:
e = util.parse_election('r2b2/tests/data/election_template.json')

In [31]:
e

Election: [ElectionName, 10000, [Contest: [100, {'CandidateA': 50, 'CandidateB': 50}, 1, ['CandidateA'], <ContestType.PLURALITY: 0>], Contest: [100, {'CandidateA': 50, 'CandidateB': 50}, 1, ['CandidateA'], <ContestType.PLURALITY: 0>], ]]

In [32]:
e.contests

{'contest1': Contest: [100, {'CandidateA': 50, 'CandidateB': 50}, 1, ['CandidateA'], <ContestType.PLURALITY: 0>],
 'contest2': Contest: [100, {'CandidateA': 50, 'CandidateB': 50}, 1, ['CandidateA'], <ContestType.PLURALITY: 0>]}

In [33]:
e.name

'ElectionName'

In [34]:
e.total_ballots

10000